<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for the system_cron_settings() form.
 */
function usage_cron_form_system_cron_settings_alter(&$form, &$form_state) {
  $usage_cron_settings = \Drupal::config('usage_cron.settings');

  $form['usage_cron'] = [
    '#title' => t('Usage cron settings'),
    '#type' => 'details',
    '#open' => TRUE,
  ];

  $options = [1, 900, 1800, 3600, 10800, 21600, 43200, 86400, 604800];
  $form['usage_cron']['min_interval'] = [
    '#type' => 'select',
    '#title' => t('Run usage cron no more often than every'),
    '#description' => t('When the site is under constant usage, the usage cron will fire this often, less often during periods of intermittent use, and never if the site is not used.  Only processes registered with <code>hook_usage_cron</code> will be executed by the Usage Cron.',),
    '#default_value' => $usage_cron_settings->get('min_interval'),
    '#options' => [0 => t('Never')] + array_map([
        \Drupal::service('date.formatter'),
        'formatInterval',
      ], array_combine($options, $options)),
  ];

  // Add submit callback.
  $form['#submit'][] = 'usage_cron_settings_submit';

  // Theme this form as a config form.
  $form['#theme'] = 'system_config_form';
}

/**
 * Form submission handler for system_cron_settings().
 */
function usage_cron_settings_submit(array $form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('usage_cron.settings')
    ->set('min_interval', $form_state->getValue('min_interval'))
    ->save();
}
