# Schema for the configuration files of the Automated cron module.

automated_cron.settings:
  type: config_object
  label: 'Usage cron settings'
  mapping:
    min_interval:
      type: integer
      label: 'Run usage cron no more often than every'
